
subductions = {}
# Meson subductions on axis
subductions[("A1", "g", 1)] = ["A1"]
subductions[("A1", "u", 1)] = ["A2"]
subductions[("A2", "g", 1)] = ["B1"]
subductions[("A2", "u", 1)] = ["B2"]
subductions[("E", "g", 1)]  = ["A1", "B1"]
subductions[("E", "u", 1)]  = ["A2", "B2"]
subductions[("T1", "g", 1)] = ["A2", "E"]
subductions[("T1", "u", 1)] = ["A1", "E"]
subductions[("T2", "g", 1)] = ["B2", "E"]
subductions[("T2", "u", 1)] = ["B1", "E"]
# Meson subductions planar diagonal
subductions[("A1", "g", 2)] = ["A1"]
subductions[("A1", "u", 2)] = ["A2"]
subductions[("A2", "g", 2)] = ["B2"]
subductions[("A2", "u", 2)] = ["B1"]
subductions[("E", "g", 2)]  = ["A1", "B2"]
subductions[("E", "u", 2)]  = ["A2", "B1"]
subductions[("T1", "g", 2)] = ["A2", "B1", "B2"]
subductions[("T1", "u", 2)] = ["A1", "B1", "B2"]
subductions[("T2", "g", 2)] = ["A1", "A2", "B1"]
subductions[("T2", "u", 2)] = ["A1", "A2", "B2"]
# Meson subductions cubic diagonal
subductions[("A1", "g", 3)] = ["A1"]
subductions[("A1", "u", 3)] = ["A2"]
subductions[("A2", "g", 3)] = ["A2"]
subductions[("A2", "u", 3)] = ["A1"]
subductions[("E", "g", 3)]  = ["E"]
subductions[("E", "u", 3)]  = ["E"]
subductions[("T1", "g", 3)] = ["A2", "E"]
subductions[("T1", "u", 3)] = ["A1", "E"]
subductions[("T2", "g", 3)] = ["A1", "E"]
subductions[("T2", "u", 3)] = ["A2", "E"]
# Meson subductions 2 on axis
subductions[("A1", "g", 4)] = ["A1"]
subductions[("A1", "u", 4)] = ["A2"]
subductions[("A2", "g", 4)] = ["B1"]
subductions[("A2", "u", 4)] = ["B2"]
subductions[("E", "g", 4)]  = ["A1", "B1"]
subductions[("E", "u", 4)]  = ["A2", "B2"]
subductions[("T1", "g", 4)] = ["A2", "E"]
subductions[("T1", "u", 4)] = ["A1", "E"]
subductions[("T2", "g", 4)] = ["B2", "E"]
subductions[("T2", "u", 4)] = ["B1", "E"]
# Meson subductions misc
subductions[("A1", "u", 5)] = ["A2"]
subductions[("A1", "u", 6)] = ["A2"]

# Baryon subductions onaxis
subductions[("G1", "g", 1)] = ["G1"]
subductions[("G1", "u", 1)] = ["G1"]
subductions[("G2", "g", 1)] = ["G1"]
subductions[("G2", "u", 1)] = ["G2"]
subductions[("H", "g", 1)]  = ["G1", "G1"]
subductions[("H", "u", 1)]  = ["G2", "G2"]

# Baryon subductions planar diagonal
subductions[("G1", "g", 1)] = ["G1"]
subductions[("G1", "u", 1)] = ["G1"]
subductions[("G2", "g", 1)] = ["G1"]
subductions[("G2", "u", 1)] = ["G2"]
subductions[("H", "g", 1)]  = ["G1", "G1"]
subductions[("H", "u", 1)]  = ["G2", "G2"]
# Baryon subductions planar diagonal
subductions[("G1", "g", 2)] = ["G"]
subductions[("G1", "u", 2)] = ["G"]
subductions[("G2", "g", 2)] = ["G"]
subductions[("G2", "u", 2)] = ["G"]
subductions[("H", "g", 2)]  = ["G", "G"]
subductions[("H", "u", 2)]  = ["G", "G"]
# Baryon subductions cubic diagonal
subductions[("G1", "g", 2)] = ["G"]
subductions[("G1", "u", 2)] = ["G"]
subductions[("G2", "g", 2)] = ["G"]
subductions[("G2", "u", 2)] = ["G"]
subductions[("H", "g", 2)]  = ["F1", "F2", "G"]
subductions[("H", "u", 2)]  = ["F1", "F2", "G"]
